### ISSUE TITLE
Dynamic amount in actions.transactions.amount.total

### ISSUE THREAD

**Issue by inmogr** [keeperofchem/ng4-paypal-button#3]
Hi,

I would like to know how to make the amount's total dynamic currently you have put static string for the amount. but i want to change it dependence on the items selected so the payment can be completed.

**Comment by KevinShiCA** [comment]
Hi, sorry for the late reply. 
You can create a member of the class and use that. I added an example to the project.

```
public paymentAmount: number = 5; // change elsewhere

// in paypalConfig
payment: (data, actions) => {
  return actions.payment.create({
    payment: {
      transactions: [
        { amount: { total: this.paymentAmount, currency: 'CAD' } }
      ]
    }
  });
}
```

**Comment by inmogr** [comment]
Hi,

Thanks a lot for your support. I have tried this method but I'm getting error of "undefined" the inner function is not able to read the global variables

**Comment by KevinShiCA** [comment]
I am unable to reproduce this. Is this occuring during AOT compilation or during a simple ng serve?

**Comment by inmogr** [comment]
It is occurring during ng serve, compilation goes well till i click on paypal button then it shows error. therefore, i tried to test by logging the event so it shows the global variable as undefined.

**Comment by KevinShiCA** [comment]
Is this occuring in this repo or your own project? The only bug I have found in this repo is that the payment amount cannot fall below 0, everything else seems to be working.

**Comment by inmogr** [comment]
thanks for your help

it is happening in my own project, but i copied your component into my project as a whole for test but still this is happening

**Comment by KevinShiCA** [comment]
Have you tried cloning and running the repo on its own?

**Comment by inmogr** [comment]
Not yet, I'll try cloning it today n update you.

Thank you so much

**Comment by inmogr** [comment]
Hi,

So sorry for the delay to reply I went so busy. I have just tested the code as you provided and it runs well. Thanks a lot for your support.
